### ISSUE TITLE
Change Typo on getting started screen

### ISSUE THREAD

**Issue by alexanderboerger** [trustlines-network/feedback#10]
### Basic information first:

* OS (iOS): 
* Version: 1.0.15 

### Issue description:

I think you already know this, don't use a black font, don't have it so close to the border.

### Screenshots

*please provide screenshots on any UI related issue*
![img_4870](https://user-images.githubusercontent.com/19476957/35388396-e93e8232-01d3-11e8-80cc-f6ef72d0ab5b.PNG)

**Comment by jensneuber** [comment]
done

**Comment by Kispus** [comment]
Closing issue as it has been tested and changed according to the description. Future design needed on the current positioning / white box needed.
