### ISSUE TITLE
Username is not saved. 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#100]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 

### Issue description:
After editing the username, hitting enter on the keyboard will not save the username, it is really easy to overlook to press done. Also there is no warning when you leave the screen.

**Comment by Kisgus** [comment]
Any thoughts on this @pixerizer ? What would you recommend?

**Comment by seichris** [comment]
I think @pixerizer would say that it should just work, confirming with the keyboard key.

Its rather a question to @jensneuber if its technically possible. (If you say it is then i'll put it on the testing board)
