### ISSUE TITLE
Should a request link be invalidated after it's clicked

### ISSUE THREAD

**Issue by jensneuber** [trustlines-network/feedback#101]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:
Should a request link be invalidated after it's clicked

**Comment by Kisgus** [comment]
Yes that would be nice. Same if you also "decline" a request

**Comment by seichris** [comment]
yes

**Comment by seichris** [comment]
the current solution is better, because it doesnt need fixes in the backend.
https://github.com/trustlines-network/feedback/issues/212
