### ISSUE TITLE
Typo in add contact messsage 

### ISSUE THREAD

**Issue by jensneuber** [trustlines-network/feedback#103]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:
There is a type in the message that is prepared for "Share my contact"

**Comment by Kisgus** [comment]
More info needed

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
Referring to "Share me" link or which typo was fixed here @jensneuber ?

**Comment by Kisgus** [comment]
Tested & confirmed fixed, as covered in https://github.com/trustlines-network/feedback/issues/108
