### ISSUE TITLE
Scanner from main navigation not working but scanner by clicking + is

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#104]
### Basic information:

OS (Android / iOS / both): Android Samsung galaxy alpha 4.4
Version: 1.0.18 (1528815062)

### Screenshots or mock-ups

![image 2018-06-13 15 50 02](https://user-images.githubusercontent.com/18598519/41355293-705f6302-6f21-11e8-870a-4f7127c93477.jpg)

![image 2018-06-13 15 50 05](https://user-images.githubusercontent.com/18598519/41355297-71ad17e0-6f21-11e8-8b07-76edf6490540.jpg)

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
Tested and works on iOS, + Android Experia + Honor phones
