### ISSUE TITLE
Open qr code freezes the app on hibernate. 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#105]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 
1.0.18 v26
### Issue description:
When I have the qr code view open and the phone starts sleeping, after resuming the qr code is gone and the app hangs. Closing and reopening the app will show the qr code again.

**Comment by jensneuber** [comment]
fixed

Fixed by closing the QR code modal on switch to background mode
please test this thoroughly on Android!

**Comment by krisnaer** [comment]
Phone: Sony Xperia XA1
OS: Android 8.0.0

This issue did not occur for me.

**Comment by cducrest** [comment]
Phone: Samsung Galaxy Alpha
Android 4.4.4

The issue was fixed for me as well.

**Comment by Kisgus** [comment]
Thanks for the input
