### ISSUE TITLE
The ETH costs are not shown when sending a transfer. 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#107]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 
1.0.18

### Issue description:
When I do a normal trustlines transfer it only shows the trustlines fees and never the ETH fees. 

### Screenshots or mock-ups

![networkfees](https://user-images.githubusercontent.com/25006584/44719372-6387f800-aac3-11e8-9944-bdeaa0e86bce.JPG)

**Comment by pepae** [comment]
Probably insufficient decimal digits, right?

**Comment by Kisgus** [comment]
@jensneuber @berndbohmeier should information already be available from the relay server at this point or not?

**Comment by berndbohmeier** [comment]
The information is available as this is decided by the client. Additionally the relay server gives a hint how much to chose. This clientlib returns that value.

**Comment by Kisgus** [comment]
Okay thanks for the clarification. How about the fees displayed on a payment receipt? 
Is this also available information for the app at this point?

**Comment by berndbohmeier** [comment]
Nope, this is sadly not available atm.

**Comment by berndbohmeier** [comment]
But we could for example show the confirmation status on the receipt maybe?

**Comment by Kisgus** [comment]
Yes that would be very nice to have available as well. As suggested by you I will create an user-story on the confirmation enabling the user to see whether a tx is pending, confirmed or timed-out

**Comment by seichris** [comment]
@berndbohmeier did you open an issue for the relay server?

**Comment by berndbohmeier** [comment]
This issue is about sending a transfer. Everything is there in the clientlib and the relay, the app just have to show it.

**Comment by seichris** [comment]
Sweet. Then @jensneuber is the info above enough for you to implement this feature?

**Comment by dakingha69** [comment]
implemented via https://github.com/trustlines-network/mobileapp/compare/3b883564c629...948e7a78a900
