### ISSUE TITLE
Spelling mistake in "add me" link

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#108]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:

truslines instead of trustlines

### Screenshots or mock-ups

![63822071-a600-454e-83d6-04ed5206f1ce](https://user-images.githubusercontent.com/18598519/41355819-a6aee120-6f22-11e8-90c8-8ca1bdee16d0.jpg)

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
Tested and indeed fixed :)
