### ISSUE TITLE
Show the QR code on the onboarding screen

### ISSUE THREAD

**Issue by alexanderboerger** [trustlines-network/feedback#11]
### Basic information first:

* OS (iOS): 
* Version: 1.0.15 

### Issue description:
You can remove an unnecessary step, why do i have to press on "show QR" code if the only thing i can do is to show my qr code?

### Screenshots
![img_4871](https://user-images.githubusercontent.com/19476957/35388447-24c2e80c-01d4-11e8-8249-8a3b2094813e.PNG)

*please provide screenshots on any UI related issue*

**Comment by Kispus** [comment]
yes ok @alexanderboerger I see your point, but showing your QR_code is not the only thing you can do here, you can also 1) send link 2) copy eth address 

We might consider having the QR code already visible here in the future, but currently this will not be changed.

**Comment by Kisgus** [comment]
Overlapping #32
