### ISSUE TITLE
Loading screen for onboarding

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#110]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s
* Version: 1.0.18 / v26

### Issue description:
UX: While Jens' onboarding transaction goes through, I would love to see an indicator that the transaction is on the way.

The process of onboarding needs the most help. Since new users don't know anything about Trustlines.

### Possible solution
Have some (better than a circle) loading animation

**Comment by Kisgus** [comment]
@seichris you mean when the one user is sending a trustline request for the other?? What do you have in mind here? Animation or tutorial or something else?

**Comment by seichris** [comment]
In the onboarding situation: I wait for the transaction.

I would love to have a short tutorial in the start:
I see the screen with an overlay and it guides me to my QR code. Then i click "got it. done". Then i see a loading screen, where i see the number of confirmation on testnet or whatever.
When i got the transaction of eth, i can start using the app. That could also very well work with an explainer tutorial.

The issue also works for the whole app. The loading process could be something more specific. Something which explains what is happening better than a loading circle

**Comment by Kisgus** [comment]
Great point!

**Comment by seichris** [comment]
Moved to https://github.com/trustlines-network/design/issues/24
