### ISSUE TITLE
Not immediately intuitive where the total balance is

### ISSUE THREAD

**Issue by pepae** [trustlines-network/feedback#113]
### Basic information:

* OS (Android / iOS / both): 
* Version:

**Comment by Kisgus** [comment]
Proposed solution @pepae ?

**Comment by pepae** [comment]
Put it underneath the available

**Comment by Kisgus** [comment]
You mean to have all 4 values shown by default on "Overview" ? Or just available and balance?

**Comment by seichris** [comment]
implemented in current mockups
