### ISSUE TITLE
Wording Trustline agreement slightly misleading

### ISSUE THREAD

**Issue by pepae** [trustlines-network/feedback#115]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:

"How much are you willing to lend/owe" sounds like you're actually giving a loan, whereas you're just opening a credit line here, for someone to draw on that line in the future

### Possible solution

Maybe easily solved by adding "maximally lend/owe"

**Comment by Kisgus** [comment]
"How much are you maximally willing to lend?" that is your best proposal @pepae ?

**Comment by seichris** [comment]
_Contract_ is better.

And i like _maximally lend/owe_.
