### ISSUE TITLE
Confirmation pop up pops up too late

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#116]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s
* Version: 1.0.18 / v26

### Issue description:
Schmir had this problem.
First he sent a Trustline request to Jens(?!). And there was no confirmation.
Then he did something else. And after a while the confirmation popped up.

### Screenshots or mock-ups
![trustlines](https://user-images.githubusercontent.com/25006584/41359910-d1e1da56-6f2b-11e8-8fc9-387b5f619098.png)

### Possible solution
Loading screen somewhere, when an action takes longer than "immediately"

**Comment by jensneuber** [comment]
fixed

a loading modal in the background is display during the confirmation process which does not let the user interfere with the app

**Comment by Kisgus** [comment]
Neither Kris or I can reproduce on our iOS / Android devices, can you reproduce this @schmir ???

**Comment by schmir** [comment]
I wasn't able to reproduce this.

**Comment by Kisgus** [comment]
Ok thanks
