### ISSUE TITLE
Payment does not work over selecting contact

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#117]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, Android 7
* Version: 1.0.18 / v26

### Issue description:
Payment does not work over selecting contact.  I go over "Overview" --> "send"  --> enter amount --> select contact

**Comment by Kisgus** [comment]
@seichris Lets discuss how this could be changed, would be very interested in seeing a proposal from you

**Comment by seichris** [comment]
This issue now is in the design repo, under https://github.com/trustlines-network/design/issues/2#issuecomment-402765762
