### ISSUE TITLE
Send request-money link cuts the last letter

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#118]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, Android 7
* Version: 1.0.18 / v26

### Issue description:
Sending the link through whatsapp, it cuts the last letter of the subject i entered.

**Comment by Kisgus** [comment]
So the context is you included a message in the request-money link and shared it in Whatsapp @seichris ?

**Comment by seichris** [comment]
>So the context is you included a message in the request-money link and shared it in Whatsapp @seichris ?

Exectement!

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
Fixed, and indeed now the full length is displayed
