### ISSUE TITLE
Onbording Confirm Screen does not show ETH to be sent

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#119]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 
1.0.18 v26

### Issue description:
After scanning an onboarding request the confirm screen only shows xxx for the ETH amount to be send.

**Comment by Kisgus** [comment]
@jensneuber is this available information to show?

**Comment by berndbohmeier** [comment]
Should be available, as this is decided on the client.

**Comment by jensneuber** [comment]
done

I adopted the 0.1 eth from the clientlib and made it configurable in the app config

**Comment by Kisgus** [comment]
Tested and it works by showing 1) The 0.1 ETH transferred and 2) max gas eth payable
