### ISSUE TITLE
Onboarding "relaying" error

### ISSUE THREAD

**Issue by Kispus** [trustlines-network/feedback#12]
### Basic information first:

* OS (Android / iOS / both):  Detected both on IOS and Android
* Version: Android & IOs newest 

### Issue description:

When trying to onboard new users (Alex & Chris) I get this error from my account. I have doubble checked that we are in the same EUR network, and that my account has ETH.

When I create a new account, and navigate to advanced options, and reload 1 ETH, I can send one onboarding request to Chris after scanning his QR code. After updating his screen manually, there are however no CreditlineRequest on Chris' screen. 
When I try to scan Alex' account from the same (new account) the same error as show below is repeated as from the initial account.

### Screenshots

![img_2978 2](https://user-images.githubusercontent.com/18598519/35388430-16886500-01d4-11e8-9798-2c905861957b.PNG)

*please provide screenshots on any UI related issue*

**Comment by jensneuber** [comment]
**Findings: **
Response from relay server:
Status 409: There was an error while relaying this transaction

Log entry from parity server: 
Error importing transaction: Transaction(InsufficientBalance { balance: 1000000000000000000, cost: 99999999999999991611392 })

**Comment by jensneuber** [comment]
done

**Comment by Kispus** [comment]
Closing as I can now have contact to the Relay and add trustlines and send transactions on android / iphone, ty!
