### ISSUE TITLE
Transaction details doesn't show subject

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#120]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, Android 7
* Version: 1.0.18 / v26

### Issue description:
Coming from overview, going into transaction details i don't see any subject

**Comment by jensneuber** [comment]
changed title to represent the problem better

**Comment by jensneuber** [comment]
I will disable it, even if we are going to integrate this feature soon.

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
Thanks, tested and fixed aka the feature has been disabled :)
