### ISSUE TITLE
"View Currency" in "Me" screen is unnecessary

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#121]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, Android 7
* Version: 1.0.18 / v26

### Issue description:
"View Currency" in "Me" screen:
Why do we have this screen? Shouldn't it be the same as the network overview sidebar?

**Comment by Kisgus** [comment]
That is a good question @seichris Yes actually right now clicking the expanded "Available" from "Overview" displays the same information as "Currency"

**Comment by seichris** [comment]
This just needs a decision and implementation would be easy.

**Comment by Kisgus** [comment]
Okay, I would align this with Basems work on where to display / have an overview of different types of trustline networks and currencies such as Ethereum
