### ISSUE TITLE
Prompt for a name when creating the account

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/feedback#122]
### Basic information:

* OS (Android / iOS / both): Samsung Galaxy Alpha - Android 4.4.4
* Version: 1.0.18 (1528815062)

### Issue description:
It could be nice to ask what name to put for the person when he signs up.

**Comment by jensneuber** [comment]
Do you mean instead of creating a random username?

**Comment by Kisgus** [comment]
In a real production ready version (where the name is also messaged to the counterparty) I totally agree @cducrest 
Right now this is however simply the easiest way to get a user started from my point of view

**Comment by cducrest** [comment]
You could leave the random username as a default value in case someone does not want to enter his name / a pseudonym. But it might be confusing to user that they are attributed a name without them knowing about it.

**Comment by Kisgus** [comment]
Yes that is true, that might be a possibility. Right now the only info given is "your name is generated" I envisage we would in turn enable the user to log-in with a 3rd party service, which would also then 1) make it easy to get started 2) transfer the name from the service

**Comment by seichris** [comment]
implemented in current mockups
