### ISSUE TITLE
its unclear how "backup" works

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#123]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, Android 7
* Version: 1.0.18 / v26

### Issue description:
Looks weird. Dont know what this is. 
How can i upload this backup to another app? There is no feature to enable this.

### Possible solution
Write a little guide on the "backup" page.
And have a backup feature where i can copy in my backup text to get my data back.

**Comment by Kisgus** [comment]
You refer to "Backup Data" @seichris ?

**Comment by seichris** [comment]
> You refer to "Backup Data" @seichris ?

yea. i dont understand what actually is backed up.
And i dont get how to import the data again.

**Comment by seichris** [comment]
moved to https://github.com/trustlines-network/design/issues/23
