### ISSUE TITLE
Share address / share link in the "Me" tab

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/feedback#125]
### Basic information:

* OS (Android / iOS / both): Samsung Galaxy Alpha - Android 4.4.4
* Version: 1.0.18 (1528815062)

### Issue description:
It could be more intuitive to have the option to share address or link in the "Me" tab, below "QR code", instead or at the same time as in the side menu that comes up when you press "+" on the top right corner of the "Overview" tab.

![photo_2018-06-13_16-38-49](https://user-images.githubusercontent.com/17010722/41358253-4650455c-6f28-11e8-994e-fe76bac4e3b0.jpg)

**Comment by seichris** [comment]
implemented this into the current mockups
