### ISSUE TITLE
Usually I see Andreas' user pic round. But once its a square

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#127]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, Android 7
* Version: 1.0.18 / v26
![squared andreads](https://user-images.githubusercontent.com/25006584/41358443-acaa43c0-6f28-11e8-8050-149f5259052f.jpg)

### Issue description:
Usually I see Andreas' user pic round. But once its a square

**Comment by Kisgus** [comment]
Yes true this is Android only, I have not detected any on iOS

So far 1) Quarter circles 2) Rectangle 3) Triangle detected.... :)

Which identicon library are we using @jensneuber ? Do you have any ideas about what might cause this @berndbohmeier ?

**Comment by jensneuber** [comment]
Tested a different shape lib, same results though. Might be solved by making overlay png.

**Comment by berndbohmeier** [comment]
With the new update it is now even worse. It flickers between circle and rectangular while scrolling.

**Comment by jensneuber** [comment]
Next try. We have an PNG overlay now. Please test again

**Comment by seichris** [comment]
fixed
