### ISSUE TITLE
Creating YOUR wallet pop-up

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/feedback#128]
### Basic information:

* OS (Android / iOS / both): Samsung Galaxy Alpha - Android 4.4.4
* Version: 1.0.18 (1528815062)

### Issue description:
When you first register it says "generating YOUR wallet ...", the caps lock "YOUR" seems a bit aggressive and unnecessary.

![photo_2018-06-13_16-40-32](https://user-images.githubusercontent.com/17010722/41358370-8a1bee1c-6f28-11e8-900c-822a0c44e3f3.jpg)

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
Tested and works on iOS / Android thanks.
