### ISSUE TITLE
Directing to "Home" instead of "Profile" after wallet has been genereated

### ISSUE THREAD

**Issue by Kispus** [trustlines-network/feedback#13]
### Basic information first:

* OS (Android / iOS / both):  IOs & Android
* Version: Newest

### Issue description:

After I sign up & join trustlines network I am directed to "Home" and not "Profile" which gives me another step of getting onboarded, instead of directing to "Profile".

### Screenshots

![35388396-e93e8232-01d3-11e8-80cc-f6ef72d0ab5b](https://user-images.githubusercontent.com/18598519/35389135-ce9bb884-01d6-11e8-89ac-473f911cf2cc.png)

**Comment by jensneuber** [comment]
solved

**Comment by Kispus** [comment]
Tested on iOS and Android, and can confirm it not directs to Profile.
