### ISSUE TITLE
"Reset app" does not remove previous accounts before the application is restarded locally

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#130]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, Android 7
* Version: 1.0.18 / v26

### Issue description:
"Reset" feature doesn't delete the private key. So whats the use of this feature?

**Comment by Kisgus** [comment]
Could you please elaborate @seichris ?

**Comment by seichris** [comment]
What does the reset feature reset?
Does the user wanna know this? I want to know it.
And i would expect the function to also delete the private key, since that is a major feature i wanna have.

So my solution would be to explain shortly what it does. And make it delete the private keys from the phone.

**Comment by seichris** [comment]
Moved to design https://github.com/trustlines-network/design/issues/23

**Comment by krisnaer** [comment]
![photo6010442135729450921](https://user-images.githubusercontent.com/29100596/43906777-619f463e-9bf4-11e8-8f60-0b24c3bc55be.jpg)

**Comment by jensneuber** [comment]
solved

**Comment by seichris** [comment]
works for me
