### ISSUE TITLE
Infinite loading loop, after clicking on "me"

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#133]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, Android 7
* Version: 1.0.18 / v26

### Issue description:
If i click on me, i have a infinitive loading loop at the top of the screen

**Comment by Kisgus** [comment]
Related to https://github.com/trustlines-network/feedback/issues/102

**Comment by jensneuber** [comment]
fixed .. please test again

in any android build >= 1529340467

**Comment by seichris** [comment]
works for me :)

**Comment by Kisgus** [comment]
@berndbohmeier Please put in screenshot here from infiinite loading loop on "overview"

**Comment by berndbohmeier** [comment]
dont have one :/

**Comment by Kisgus** [comment]
We detected this again today @jensneuber on the "Overview" screen on Bernds phone.

**Comment by Kisgus** [comment]
Might be related to #145

**Comment by jensneuber** [comment]
@Kisgus nope this is unrelated

**Comment by berndbohmeier** [comment]
Sorry, could not reproduce it so far. Will report back if I see it again. I think it was after onboarding

**Comment by seichris** [comment]
fixed
