### ISSUE TITLE
UI Proposal: change the "contact" -> "trustlines events" screen

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#134]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, Android 7
* Version: 1.0.18 / v26

### Issue description:
In contact list, long click on user pic should enable you to upload new user pic. Long click on name should enable you to change name.

Clicking on a user in the address list:
-> like it is now: see all transactions and updates, but change:
- cut see weird symbol
- take some symbol instead of FUGGERS user pic
- enable filtering for the list by clicking on a EURO symbol, USD symbol etc.
- clicking on details you get to a Trustline statistics page. for one TL in one network

### Screenshots or mock-ups
https://www.figma.com/proto/IXIqYNS6WPLMtMQkvlE31PqO/Trustlines-UI?scaling=contain

Contacts:
Click on "Dongha"
Trustlines Events:
Click on "Trustline Details"
Trustline Details:
All statistics.

**Comment by Kisgus** [comment]
@seichris great work! Please elaborate this to me in person

**Comment by seichris** [comment]
This issue now is in the design repo, under https://github.com/trustlines-network/design/issues/2#issuecomment-402765762
