### ISSUE TITLE
Generating wallet message is not showing long enough

### ISSUE THREAD

**Issue by jensneuber** [trustlines-network/feedback#135]
### Basic information:

* OS (Android / iOS / both): both
* Version: all

### Issue description:
The "Generating wallet" message is not showing long enough to be able to read it

### Possible solution
Prolong the appearance

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
@krisnaer was this fixed or not?

**Comment by krisnaer** [comment]
I still find this to be relatively short. It took 15 seconds to generate my wallet. The message was there for ~4 seconds. I would consider prolonging the message to 8 seconds.

**Comment by jensneuber** [comment]
On android there are only two options for the display duration of a toast, SHORT and LONG. 
SHORT seems to be 2 sec., LONG 3.5 sec. 
This is the maximum I can do right now

**Comment by krisnaer** [comment]
Ok fair enough. [I found a workaround](https://blog.cindypotvin.com/toast-specific-duration-android/) but I'm not sure if it's worth the extra lines of code.

**Comment by jensneuber** [comment]
@krisnaer Thanks for the info! We are not writing the app in Java, so the above example won't solve our issue, but I will look into this, if there is a solution like this for JS.

**Comment by Kisgus** [comment]
As of now I consider this issue done. It seems to be not very easy to fit this to everyphone based on the information in this screen
