### ISSUE TITLE
Show warning if running low on ETH

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#136]
### Issue description:
There should be a warning if you are low on ETH, say 0.01 ETH. 

### Screenshots or mock-ups

![low eth](https://user-images.githubusercontent.com/25006584/44660824-25c69900-aa09-11e8-8db9-3170eeb197ec.JPG)

**Comment by Kisgus** [comment]
Should it say "you are low on ETH" or say "You can only do x more (estimated) transactions?"

**Comment by berndbohmeier** [comment]
I think "you are low on ETH" is better than nothing. We can not really do a good estimation, as trustlines updates are the most expensive operation for example, and transfer costs depend on the hops.

**Comment by jensneuber** [comment]
should it be temporary (lets say after a balance update ) or permanent on the overview screen?

**Comment by berndbohmeier** [comment]
I would like it to be permanent but maybe the user could be able to remove the warning.

**Comment by jensneuber** [comment]
ok. Remove for how long? 
Should it reappear after some time? Should it re-appear after the user got eth and than gets below the threashold again?

**Comment by seichris** [comment]
I think:

If user got less than eth equaling ~5 transactions, then you should show a warning. Show it until the user gets more eth.

The user can click on the sentence and comes to the receive-ether screen.

![low eth](https://user-images.githubusercontent.com/25006584/44660824-25c69900-aa09-11e8-8db9-3170eeb197ec.JPG)

**Comment by berndbohmeier** [comment]
0.01 eth as the threshold would be about ~3-10 transaction depending on the hops, gas price etc.

**Comment by berndbohmeier** [comment]
> Should it reappear after some time? Should it re-appear after the user got eth and than gets below the threashold again?

I would say for a first version it is fine if it just stays.

**Comment by seichris** [comment]
@jensneuber is that info enough for you to implement the feature?

**Comment by seichris** [comment]
Being worked on in here: https://github.com/trustlines-network/mobileapp/issues/324
