### ISSUE TITLE
Bug when resetting app_data

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#137]
### Basic information:

* OS (Android / iOS / both): Both
* Version: Newest 1.018

### Issue description:

When resetting the app_data from: Me -> Version -> Reset App ->  I am directed to start-screen and then directed to the below screen

### Possible solution

Only direct to start-screen

**Comment by krisnaer** [comment]
### Basic information:

* OS (Android / iOS / both): Android 8.0.0
* Version: 1.0.18 (1529324815)

### Issue description:

1. Reset button crashes the app see the first screenshot.
2. Reset button does not remove the account that I've reset from the login menu (see the second screenshot). 

### Screenshots or mock-ups
![image](https://user-images.githubusercontent.com/29100596/41538972-db5acdd8-730c-11e8-977d-f7fe1fd97780.png)

![image](https://user-images.githubusercontent.com/29100596/41539069-1ee0828c-730d-11e8-8d8d-777c6b22a2c4.png)

**Comment by jensneuber** [comment]
should be solved

**Comment by seichris** [comment]
fixed for me
