### ISSUE TITLE
'undefined is not an object' while trying to send trustline agreement

### ISSUE THREAD

**Issue by schmir** [trustlines-network/feedback#138]
### Basic information:

* OS (Android / iOS / both): 
Android 7

### Issue description:
I get 'undefined is not an object' error, when I click the 'sign' button.

### Screenshots or mock-ups

![screenshot_20180619-103516](https://user-images.githubusercontent.com/40620/41586510-383222cc-73ad-11e8-8ad0-b80d9cf22b77.png)

**Comment by jensneuber** [comment]
@schmir I guess only if you leave the second field empty right?

**Comment by schmir** [comment]
right, yes. If I fill in the second field, it works.

**Comment by Kisgus** [comment]
So you left one of the values blank?

**Comment by jensneuber** [comment]
@gus should a "no value" entry be treated as 0.00?

**Comment by Kisgus** [comment]
Yes, but will that still allow a user to enter into an agreement with for example 0.00 credit the one way and 15.00 credit the other way?

**Comment by seichris** [comment]
solved
