### ISSUE TITLE
Error message when sending too little value.

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/feedback#139]
### Basic information:

* OS (Android / iOS / both):  Samsung Galaxy Alpha - Android 4.4.4

* Version:  1.0.18 (1529344245)

### Issue description:

 On the menu "Overview", I click on "Send" then enter a small value such as "0.001" (basically any value below "0.01"), validate, then when I click on the contact to send the value I receive the error message that can be seen in the screenshot below. (validation error in your request).

Then if I press return to enter a different value I see the value "0." entered and not "0.001" (see screenshot).
If I first entered "0.009" and press return I will see "0.01" instead.

I am unsure this is a bug or just would be convenient to tell the user the value is too small when he enters it.

### Screenshots or mock-ups
![photo_2018-06-19_15-38-37](https://user-images.githubusercontent.com/17010722/41600696-de358a3c-73d6-11e8-9ca0-ed16abd0fb60.jpg)
![photo_2018-06-19_15-38-42](https://user-images.githubusercontent.com/17010722/41600697-de50d8e6-73d6-11e8-8730-2920bfdb1a95.jpg)

**Comment by jensneuber** [comment]
Input beyond the networks decimal is prevented now

**Comment by cducrest** [comment]
I confirm that this works on my phone.

**Comment by seichris** [comment]
Works for #metoo
