### ISSUE TITLE
whatsapp doesn't show TL link as clickable link

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#14]
### Basic information first:

* Android 7.0 - MIUI 9 - Xiaomi 5S

### Issue description:
- My account name is `Chris Test #w`. (Separated by a `space`)
- Share `get started` link into whatsapp
- Link does not fully show as link, because of the space.

Solution: 
- allow only names without spaces
- convert `spaces` into `_`
- different link?!

### Screenshots

![2080654814](https://user-images.githubusercontent.com/25006584/35396553-59739ca4-01ed-11e8-8044-d5c53528fdf5.jpg)

**Comment by Kispus** [comment]
Works on IOS from what I can tell.

**Comment by Kispus** [comment]
@seichris Do you still encounter this problem??

**Comment by seichris** [comment]
yes, whatsapp will always show it like this.

I suggest you pick this solution:
convert `spaces` into `_`

**Comment by Kisgus** [comment]
Fixed.
