### ISSUE TITLE
Error message and effective transaction after double confirms

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/feedback#140]
### Basic information:

* OS (Android / iOS / both): Samsung Galaxy Alpha - Android 4.4.4
* Version: 1.0.18 (1530276585)

### Issue description:

When I make a payment to a user, and it shows me the transaction before confirmation, I can smash the button and press it multiple times. This results in the transaction being effective AND the display of an error message: "there was an error while relaying this transaction". I guess the error message is due to the transaction being sent more than once.

### Screenshots or mock-ups

![photo_2018-06-29_17-03-16](https://user-images.githubusercontent.com/17010722/42099683-5fe0aeec-7bbe-11e8-9b42-f6a5df25be38.jpg)

![photo_2018-06-29_17-06-08](https://user-images.githubusercontent.com/17010722/42099806-bbdb7b14-7bbe-11e8-8fde-c3a604609ba1.jpg)

### Possible solution

Disable the confirm button once it was clicked.

**Comment by seichris** [comment]
cannot reproduce this anymore on my phone. no matter how fast i press the button.
