### ISSUE TITLE
Click on Trustline Update Request Notification freezes app

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#142]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 
push notification test version 1.0.18
### Issue description:
When clicking on trustline update request notification while app is closed it will open the app but only show the unicorn. 

### Screenshots or mock-ups
![screenshot_20180629-171531](https://user-images.githubusercontent.com/5587237/42100445-7bd64ce0-7bc0-11e8-8ef7-ac8df47f7d73.png)

**Comment by jensneuber** [comment]
should be solved now

**Comment by seichris** [comment]
notifications dont work for me, so cannot test this. @berndbohmeier can you test please

**Comment by jensneuber** [comment]
why do notifications not work for you? try to switch off and on under "Me" -> "Version" if you do not receive Push notifications

**Comment by seichris** [comment]
Works now :) will test the above
