### ISSUE TITLE
Indefinite loading-loop when scanning Coms onboarding QR code 

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#145]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:

After scanning onboarding QR code my phone freezes and the below happens

### Screenshots or mock-ups

![img_3567](https://user-images.githubusercontent.com/18598519/42278159-22f84cee-7f9a-11e8-8679-9e63e67bc6c0.png)

**Comment by Kisgus** [comment]
Tested (on newest iOS)  and after scanning a fresh "on_board me" QR from Chris' mobile the following happens now:
![img_3578](https://user-images.githubusercontent.com/18598519/42566704-b6ed7af6-8507-11e8-9a57-6b375aff0684.png)

![img_3579](https://user-images.githubusercontent.com/18598519/42566713-bdc01a46-8507-11e8-862a-8b2db430d245.png)

Then white-screen crash

![img_3579](https://user-images.githubusercontent.com/18598519/42566800-ffa3a248-8507-11e8-9fa8-16a8eae566be.png)


**App_center**

![screen shot 2018-07-11 at 12 42 16 pm](https://user-images.githubusercontent.com/18598519/42566805-033e5326-8508-11e8-8133-eeed43180b9c.png)


Not show up here

**Comment by jensneuber** [comment]
@Kisgus how is #144 related? Can you give more info on this?

**Comment by Kisgus** [comment]
Fixed thanks
