### ISSUE TITLE
No access to " . " when entering amounts

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/feedback#146]
### Basic information:

* OS (Android / iOS / both): Samsung Galaxy Alpha - Android 4.4.4
* Version: 1.0.18 (1530697802)

### Issue description:
When I have to enter an amount for a trustlines update, a send operation, or a receive operation, I do not have a " . "
I cannot enter 8.50 for example.

### Screenshots or mock-ups
![photo_2018-07-04_14-57-50](https://user-images.githubusercontent.com/17010722/42278411-04c32108-7f9b-11e8-8cbe-4539e625d200.jpg)

**Comment by seichris** [comment]
I do have access with my google keyboard.  @cducrest let me know if this still doesnt work for you.
