### ISSUE TITLE
Switch to toggle notifications doesn't work

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#147]
### Basic information:

Xiaomi Mi 5s, Android 7.0

### Issue description:
I click the switch. The button flashes to the left (der zuckt kurz nach links), but goes back to the right position and turns grey. I leave to the _Me_ tab, then go into _Version_ again. And the button is to the right and red again.

Also my notifications don't work, although its switched on.

### Screenshots or mock-ups
![431715099](https://user-images.githubusercontent.com/25006584/42279070-de2932d8-7f9c-11e8-9064-0dc6e1676ffd.jpg)

**Comment by berndbohmeier** [comment]
probably related to the null issue
on the relay:
`relay0.testnet.trustlines.network/api/v1/pushnotifications/0xEAe37d6049E89fE0c059Da14C140EbCF025E75A0/token/null`

@seichris can you post you used address here to verify it.

**Comment by seichris** [comment]
@berndbohmeier yes thats my address.

**Comment by seichris** [comment]
now it works
