### ISSUE TITLE
Just closing and opening the app will enable push notification

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#148]
### Basic information:
If I disable push notifications in the settings of the app, I stop receiving push notifications. But if I close the app and reopen it, it will just enable push notifications again. 

* OS (Android / iOS / both): 
* Version: 

### Possible solution
Dont enable push notifications on startup of the app if the user selected to disable them.

**Comment by seichris** [comment]
I dont have this problem.

**Comment by jensneuber** [comment]
this should be solved
