### ISSUE TITLE
Slide in new screen as section of the first screen

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#15]
### Basic information first:

* Android 7.0 - MIUI 9 - Xiaomi 5S

### Issue description:
- probably more work. so this is just a proposal
why:
- because i wanna save space and clicks.

### Screenshots

![tl](https://user-images.githubusercontent.com/25006584/35397593-2e15c85e-01f0-11e8-8fee-b845c8d7e8ea.PNG)

now you click `send` and the next page slides in as a section of the homepage.

![tl 2](https://user-images.githubusercontent.com/25006584/35397660-5025cfd4-01f0-11e8-85c3-996601d858c4.jpg)

**Comment by Kispus** [comment]
Good idea @seichris for a future improvement, currently this is seen as an enhancement, and will not be implemented  in the near future.

**Comment by Kisgus** [comment]
Please bring this up again and re-open a new issue if you still think it should be changed
