### ISSUE TITLE
Some transfer never get confirmed

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#150]
### Basic information:
In the middle of all my events in the overview there are two transfer that dont have blue checkmarks.
If I log out and log in again, to force the app to reload all events, they get a blue checkmark. So I guess it 
has something to do with that at some point those events are not asked for again. 

* OS (Android / iOS / both): 
* Version: 

### Screenshots or mock-ups
![screenshot_20180704-152826](https://user-images.githubusercontent.com/5587237/42280126-221e268a-7fa0-11e8-8d94-d36327fc54e3.png)

**Comment by seichris** [comment]
Relevant issue for this app update: https://github.com/trustlines-network/mobileapp/issues/192

**Comment by jensneuber** [comment]
@berndbohmeier 
Since we do net get dedicated events when a transfer is confirmed, it might stay this way until you update manually / restart the app.

**Comment by berndbohmeier** [comment]
I tried to manually updated by pulling done, but that did not work.

**Comment by seichris** [comment]
works for me. @berndbohmeier let me know if this also is fixed for you
