### ISSUE TITLE
Push notifications dont work on Android

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#152]
### Basic information:

* OS (Android / iOS / both): Xiaomi Mi 5s, ANdroid 7.0
* Version: 1.0.18

Also Bernd tested it.

### Issue description:
Notifications don't work.

### Details

For other apps, android asks me if i want to enable notifications or any other permissions. This didn't happen for trustlines notifications.

I checked my android app settings for permissions and TL-staging got all permissions.

Sometimes my phone doesn't get (e.g. whatsapp) notifications. Because of RAM etc. But then the notifications would show up when i open the app. Even this doesn't happen with the Truslines app.

**Comment by jensneuber** [comment]
we just tested it, and it worked

**Comment by seichris** [comment]
works
