### ISSUE TITLE
User will ask for onboarding amount even if he already got ether differently

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#154]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 
1.0.18 1531314166
### Issue description:
If I scan the link of a user to set up a trustline, it will ask me to send him 0.1 eth even though he already got eth directly.

**Comment by seichris** [comment]
This issue is related to this one https://github.com/trustlines-network/project/issues/161 , where we want to see the maximum amount of TLcurrency transferable .

**Comment by jensneuber** [comment]
Should we check the contacts balance before sending the startup booster?

@Kisgus @berndbohmeier

**Comment by berndbohmeier** [comment]
That would be an option. But atm I think what is wrong is that the receiver phone shows still an onboarding code, so the sender gets the information it should onboard him.

**Comment by berndbohmeier** [comment]
I always said that I was not sure why we show different qr codes. There is the add contact and onboarding code right? I think it should always show an addme link and the sender should decide then if he needs to onboard him based on does he have eth, is he part of a network.

**Comment by seichris** [comment]
>always show an addme link

@berndbohmeier we had this issue in [the invite link issue](https://github.com/trustlines-network/project/issues/186#issuecomment-411382482) and i guess we got the same goal.

**Comment by seichris** [comment]
Problem still exists.

As solution, the app should see when there is enough eth (more than 0.15?!) and change the QR code accordingly.

**Comment by jensneuber** [comment]
I guess this is also related to https://github.com/trustlines-network/feedback/issues/189
