### ISSUE TITLE
Infinite spinner after onboarding. 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#155]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 
1.0.18 1531314166

### Issue description:
After scanning an onboarding link and set up a trustline i got the infinit spinner bug again. 

### Screenshots or mock-ups
![screenshot_20180711-154935](https://user-images.githubusercontent.com/5587237/42576510-d5b32538-8522-11e8-9fd4-092e7dac6c79.png)

**Comment by berndbohmeier** [comment]
This bug is still there with version 1.0.18 (1532522735)

**Comment by jensneuber** [comment]
Should be solved. Check for optimistic event creation while testing.

**Comment by Kisgus** [comment]
Reproduced again in  #173

**Comment by seichris** [comment]
fixed for me

**Comment by jensneuber** [comment]
@kisgus this is not related to #173 since ot is a completely different component and spinner

**Comment by Kisgus** [comment]
Ok I see
