### ISSUE TITLE
The app givs me a Status 409 error even though my tx goes throubgh

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#156]
### Basic information:

I experienced this in two cases

A) When sending "Only ETH" to Andreas

B) When extending a trustline request to Bernd

* OS (Android / iOS / both):  iOS
* Version: Version 1.0.18 (1531314625)

### Screenshots or mock-ups

![img_3588](https://user-images.githubusercontent.com/18598519/42576935-cf9094d2-8523-11e8-9a9c-6ba1955ca5ad.png)

**Comment by jensneuber** [comment]
Solved. Error was caught where it should not have been

**Comment by seichris** [comment]
fixed
