### ISSUE TITLE
Network Slider is slow

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#159]
### Basic information:

* OS (Android / iOS / both): Android 7, xiaomi 5s
* Version: 1.0.18 1532513658

### Issue description:
The network slider on both, the overview page and the contact page, are slow.
- Switching the network is slow
- The loading circle pops up. Not necessary.
- If you click one of the arrows ten times, then the network switches ten times, lagging through all of them.

### Possible solution
- Get rid of the loading circle
- If you click one of the arrows ten times, it could stop at the last？

**Comment by krisnaer** [comment]
@jensneuber the slider responds quickly for me, but as I navigate through the currency networks they are all loaded. 

So if I want to navigate from the `Work network` to the `Cash network`, I still have to load the `Beer network`.  This seems to cause unnecessary load time. 

This isn't really a bug but an enhancement. Should I create a new issue for this?

**Comment by jensneuber** [comment]
We could delay the loading of the network for a second. A quick swipe to the right one would be possible without delay. 

or we need a network selector again

**Comment by krisnaer** [comment]
Ok, so the result would be that one could quickly tab the button three times and then get navigated to the correct currency network without loading the irrelevant currency networks underway?

**Comment by seichris** [comment]
Works fine on my cheap phone.
