### ISSUE TITLE
Emptying of name on welcome screen not possible

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#162]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 
1.0.18 (1532522735)
### Issue description:
On the new sign up screens there is the screen where you can change your name. If you delete all characters in the field it will just show again the old name. It is so not possible to easy enter a new name. 

### Possible solution
Let the user also empty the field to insert a new user name. 
Best would be probably to empty the field completely if a users clicks the field, as he probably wants to enter a completely new name anyways.

**Comment by seichris** [comment]
fixed
