### ISSUE TITLE
Top right corner icon switches between scanner and + sign

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#167]
### Basic information:

* OS (Android / iOS / both): Android 7.0 Xiaomi 5s
* Version: 1.1.0-dev.0 (1533303151)

### Issue description:

The icon in the top right corner should be 'scanner' on overview and '+' sign on contacts.

For me it switched from showing 'scanner' on both pages to showing 'plus sign' on both pages.

### Screenshots or mock-ups
![plus1](https://user-images.githubusercontent.com/25006584/43718947-97cf48fe-998c-11e8-94b0-3a81799efd6d.jpg)
![plus2](https://user-images.githubusercontent.com/25006584/43718949-97eb5030-998c-11e8-9962-8a2cb46adaf2.jpg)
![scanner1](https://user-images.githubusercontent.com/25006584/43718954-9a827d64-998c-11e8-872d-0d2f6f1ab89f.jpg)
![scanner2](https://user-images.githubusercontent.com/25006584/43718955-9a9d5f4e-998c-11e8-9207-3245d050ba61.jpg)

### Possible solution
?

**Comment by seichris** [comment]
Apparently it switches from showing + to showing scanner, when you click on Account

**Comment by jensneuber** [comment]
this is solved

**Comment by seichris** [comment]
fixed
