### ISSUE TITLE
number requested to be received is not shown on the second screen of the receiving process

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#17]
### Basic information first:

* OS (Android / iOS / both): 
* Version: 7.7.1
### Issue description

The amount requested to be received is not shown on the second screen of the receiving process

### Screenshots

![receive1](https://user-images.githubusercontent.com/29100596/35402944-6018b402-01fe-11e8-96ba-2365139ced3b.jpeg)
![receive2](https://user-images.githubusercontent.com/29100596/35402953-620411c6-01fe-11e8-9e24-06d5550d1cce.jpeg) # #

**Comment by jensneuber** [comment]
we are redesigning the receive eth screen

**Comment by Kispus** [comment]
@krisnaer was did for receiving eth?
