### ISSUE TITLE
Overview doesn't show 'sent ether' event

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#175]
### Basic information:

* OS (Android / iOS / both): Android 7.0 Xiaomi Mi5s
* Version: 1.1.0-dev.5

### Issue description:

I sent 1 eth to kris. Event does not show up in overview.

### Screenshots or mock-ups
![1991043679](https://user-images.githubusercontent.com/25006584/43906423-88ead628-9bf3-11e8-8ba9-59c989fb852f.jpg)

**Comment by seichris** [comment]
Still doesn't work in 1.1.1-dev8

**Comment by Kisgus** [comment]
Currently not prioritized
