### ISSUE TITLE
Chose Ethereum network > Makes you send Work hours

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#176]
### Basic information:

* OS (Android / iOS / both): Android 7.0 Xiaomi Mi5s
* Version: 1.1.0-dev.5

### Issue description:

On overview > Ethereum tab:

Click on 'send' > Sends work hours

### Screenshots or mock-ups
![overview eth](https://user-images.githubusercontent.com/25006584/43906891-a0a21ce4-9bf4-11e8-80ef-b8bd96b684c1.jpg)

----------

![2064330791](https://user-images.githubusercontent.com/25006584/43906909-ac74c698-9bf4-11e8-9965-9b36c7b497c1.jpg)

**Comment by seichris** [comment]
I cannot reproduce it now actually.

**Comment by Kisgus** [comment]
Should no longer be relevant for newly deployed app, please reopen if the issue can still be reproduced
