### ISSUE TITLE
Typo in tutorial 

### ISSUE THREAD

**Issue by stefante** [trustlines-network/feedback#179]
### Basic information:

* OS (Android / iOS / both): Android 
* Version: 

### Issue description:
There is a typo in the Tutorial. It should read **IT** instead of **IS** 

### Screenshots or mock-ups

![screenshot_20180810-165119](https://user-images.githubusercontent.com/18031958/43965443-875f4056-9cbf-11e8-9ed3-c324bfcc5182.jpg)

### Possible solution
Change is to  it

**Comment by Kisgus** [comment]
Thanks, solved in new version of tutorial (currently was stand-in pictures and text)

**Comment by Kisgus** [comment]
Should no longer be relevant for newly deployed app, please reopen if the issue can still be reproduced
