### ISSUE TITLE
Shared contact from address book says the same message as sharing your contact

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#18]
### Basic information first:
* OS (Android / iOS / both):  Android
* Version: 7.1.1

### Issue description: 

When I share a contact stored in my address book the message displayed implies that I am also the person whose contact I am sharing

### Screenshots
![share1](https://user-images.githubusercontent.com/29100596/35403494-2ec8b74c-0200-11e8-99fa-7b06b3dd4157.jpeg)
![share2](https://user-images.githubusercontent.com/29100596/35403498-308c82f2-0200-11e8-84cf-80d4e3c3bb2d.jpeg)

**Comment by Kispus** [comment]
This is the same issue as in #11 which I cannot reproduce right now, same goes for Chris.

@krisnaer Can you still reproduce this bug?

**Comment by Kisgus** [comment]
Fixed as stated above.
