### ISSUE TITLE
Account > Currencies: Switch between currency networks functionality

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#183]
### Basic information:

OS (Android / iOS / both): Android 7.0
Version: 1.1.1-dev8

### Issue description:

This functionality is currently not supported via onboarding or when heading to "account/currencies"

### Possible solution

**A new user joining**

1. No currency networks are enabled on Overview until first trustline request is done. Instead the "Overview" is empty, and includes as (+) button to create first trustline agreement in a desired currency network

2. ETH should be opt-in and is not enabled by default

**Comment by seichris** [comment]
1. Agree. But depending on the situation, I would show the (+) button to add a contact.

2. Eth should be opt in is fine.

**Comment by seichris** [comment]
same as https://github.com/trustlines-network/feedback/issues/182

**Comment by Kisgus** [comment]
Currently not prioritized
