### ISSUE TITLE
Offer to add name to contact when accepting trustline request

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#184]
### Basic information:

OS (Android / iOS / both): Android 7.0
Version: 1.1.1-dev8

### Issue description:

After a user succesfully has entered into a trutline agreement with a contact, the user should be informed that this was succesfull, and add a name to the counterparty

**Comment by seichris** [comment]
As part of the _[verification issue](https://github.com/trustlines-network/design/issues/28)_ this will be discussed with Bernd.

**Comment by seichris** [comment]
closed for above reason
