### ISSUE TITLE
Detailed contact view

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#186]
### Basic information:

OS (Android / iOS / both): Android 7.0
Version: 1.1.1-dev8

### Possible solution

The trustline event should have the same design as the events on overview. The checkmarks should be moved away for "review". The (checkmark) does not add any value

**Comment by seichris** [comment]
The network name and amount should be clickable to come to the trustlines contract

**Comment by seichris** [comment]
Mockup:

![contact details](https://user-images.githubusercontent.com/25006584/44732710-3567df80-aae6-11e8-9eb3-09616e05546d.JPG)

**Comment by seichris** [comment]
solved for me
