### ISSUE TITLE
Account (text center and white edit text)

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#187]
### Basic information:

* OS (Android / iOS / both): Android 7.0
* Version: 1.1.1-dev8

### Issue description:

The Account title of the page is not centered. The "edit" is white, wheras it is blue in the rest of the app.

### Screenshots or mock-ups

![4760f2a2-ad79-47d7-8e2c-8285c675f46a](https://user-images.githubusercontent.com/18598519/44667421-06386c00-aa1b-11e8-9f75-139d751c4e0f.jpg)

### Possible solution

Center "Account", Make "Edit" same blue color as other "Edit" functions

**Comment by seichris** [comment]
solved for me

**Comment by Kisgus** [comment]
Same here, thanks!
