### ISSUE TITLE
Add contact screen

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#188]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:

The "Personal Link" is cutted of

### Screenshots or mock-ups

![d69de711-0414-4ef5-b304-c7cef35ac6fc](https://user-images.githubusercontent.com/18598519/44667499-37b13780-aa1b-11e8-9aba-a7234cf281d4.jpg)

### Possible solution

Dont cut it :)

**Comment by seichris** [comment]
Making a mockup

**Comment by seichris** [comment]
already in https://github.com/trustlines-network/feedback/issues/210
