### ISSUE TITLE
Refine show QR code view

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#189]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:

Current QR code does not provide alot of info, and distinguish probably between "Onboard" QR code and "Contact" QR code

### Possible solution

Please see final screenshot from Chris below

**Comment by seichris** [comment]
i love the transparency. (Showing the ethereum address and showing what else is in the link.)

I can make an extreme transparent version and then we can find something in the middle.

**Comment by Kisgus** [comment]
Cool!

**Comment by seichris** [comment]
1. Ethereum address
![qr code design](https://user-images.githubusercontent.com/25006584/44786499-9fd75900-ab94-11e8-9195-2a5bbae8a130.JPG)

2. Trustlines Link
![qr code design 2](https://user-images.githubusercontent.com/25006584/44786506-a4037680-ab94-11e8-9a06-19cbb8846e66.JPG)

**Comment by Kisgus** [comment]
I would say 1) because we can do that right away right now, not sure if for 2) we have a way to deal with short URLs off-the-shelf solution or not?

**Comment by seichris** [comment]
Two ideas:

- Short trustlines URL: trust.io/chris.eth/username
- URL shortener: goo.gl/chris.eth

**Comment by Kisgus** [comment]
I like both ideas. I would consider this part of the ENS, verification & identify reserach and right now just implement version 1.

For that I would distinguish very clearly in the text about a) onboarding QR code b) general ETH public key QR code

**Comment by Kisgus** [comment]
@seichris can we agree on asking the devs for doing 1) for now?

**Comment by seichris** [comment]
@dakingha69 we settled on these two designs for the QR code modules:

![qr codes](https://user-images.githubusercontent.com/25006584/44906115-51e95f00-ad14-11e8-8d74-582f72838927.JPG)
