### ISSUE TITLE
Directed to home instead of the requested profile when app is not open

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#19]
### Basic information first:

* OS (Android / iOS / both):  Android
* Version: 7.1.1

### Issue description: 
When clicking a "please onboard me to Trustlines" URL and the app is closed, the URL takes me to the home screen instead of the person's profile. If the app is already running, this did not occur.

### Screenshots

*please provide screenshots on any UI related issue*

**Comment by Kispus** [comment]
This is the same issue as in #11 which I cannot reproduce right now, same goes for Chris.

@krisnaer Can you still reproduce this bug?

**Comment by krisnaer** [comment]
I could only reproduce it the first time I click on the link, which I have not taken screenshots of now. The second time I click on the same contact, I am taken to an onboarding screen which does not finish loading.

![screenshot_20180129-145048](https://user-images.githubusercontent.com/29100596/35513606-f3f7b012-0503-11e8-8c82-082f3e25cec7.png)

**Comment by Kisgus** [comment]
@jensneuber did you look into this yet? :)

**Comment by Kisgus** [comment]
Lets check how this works now @krisnaer
