### ISSUE TITLE
Type indicator on send payment flow

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#190]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:

The current type indicator destroys the send/receive flow.

### Screenshots or mock-ups

![3f9e97cb-e137-4019-aab0-a721e2ee2203](https://user-images.githubusercontent.com/18598519/44667608-8959c200-aa1b-11e8-8e45-45777b0ee703.jpg)

### Possible solution

1) Short term fix would be to remove the 0.00 value, and only have the "type indicator" visible until the user press a number

2) Also include the "Currency symbol" next to the "Currency Name" below the amount

**Comment by Kisgus** [comment]
Agree @seichris ?

**Comment by jensneuber** [comment]
"destroys" as in "visually hurting" of does it disable any functionality?

**Comment by seichris** [comment]
solved for me

**Comment by Kisgus** [comment]
Same here, thanks!
