### ISSUE TITLE
Cannot find the button to edit the random name given upon account creation

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#192]
### Basic information:

* OS (Android / iOS / both): Android
* Version:  8.0.0

### Issue description:
When clicking account and selecting my username I can see the keyboard pop up and it appears as if I can change my name. However, I cannot type or delete the existing name. 

### Screenshots or mock-ups
![a044344b-a01a-4141-b2c8-7efb0f7b0726](https://user-images.githubusercontent.com/29100596/44658357-d3817a00-aa00-11e8-8a74-59d14678f267.jpeg)

**Comment by krisnaer** [comment]
I realized you have to press edit in the top right corner. So this is not a bug but instead I would suggest changing the font to make it more visible and delay the keyboard pop up until the user has actually pressed edit.

**Comment by seichris** [comment]
Its the same design issue as https://github.com/trustlines-network/feedback/issues/187

**Comment by krisnaer** [comment]
Correct
