### ISSUE TITLE
Activities missing under Contacts

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#194]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:

Even though there should be activities visible, that is not the case on "Contacts" mainpage

### Screenshots or mock-ups

![1640329670](https://user-images.githubusercontent.com/18598519/44667750-ef464980-aa1b-11e8-9666-0018e1da2da8.png)

### Possible solution

Active to see most recent event

**Comment by seichris** [comment]
works for me. only the small text is cut on the upper side

**Comment by Kisgus** [comment]
Fixed, also additional cut of bug.
