### ISSUE TITLE
Offset Position of Title in Main Screens

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/feedback#200]
### Basic information:

* OS (Android / iOS / both): Android
* Version: 1.1.1-dev.4

### Issue description:
On the main screens **Overview**, **Contacts** and **Account** the title is a bit off due to the action buttons in the upper right corner. 

### Screenshots or mock-ups
![screenshot_1535448115](https://user-images.githubusercontent.com/17645687/44714126-d473e380-aab4-11e8-90c4-9d4169184bca.png)

### Possible solution
Adjust position of title in main screens.

**Comment by Kisgus** [comment]
Same as #188
