### ISSUE TITLE
Loading screen shows wrong color

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#203]
### Basic information:

* OS (Android / iOS / both):
Android
* Version: 
1.1.1-dev8
### Issue description:
After clicking send the whole screen will become slightly red for a very short moment. This color looks off, probably a leftover from before.

**Comment by dakingha69** [comment]
Fixed via https://github.com/trustlines-network/mobileapp/compare/537d01c73e18...58121e75cbf7
