### ISSUE TITLE
The greyed out text indicating next network is cutted off

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#206]
### Basic information:

Like below

### Screenshots or mock-ups

![image 2018-08-31 09 38 02](https://user-images.githubusercontent.com/18598519/44899260-90c1e980-ad01-11e8-8fd2-caaffb1b4584.jpg)

**Comment by berndbohmeier** [comment]
Which version is that. I dont even see that text at all?

**Comment by Kisgus** [comment]
Development branch app version. Jens should have fixed it now.

**Comment by Kisgus** [comment]
Done
