### ISSUE TITLE
Develop_Branch_Wrap_Up

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#207]
### Basic information:

Below is a list of minor layout bugs

- [x] When opening app, switch to Contacts  #182 
- [x] Make new design on buttons  in receive payment flow & 'Copy address' should have same icon and same color as on _Account_
- [x] Change from white to blue scanner icon in sent/receive flow 
- [x] Fix cutted off text on Overview & "Add Contacts"
- [x] In the onboarding slider the top margin is not right. give it the same amount of pixels as the margin to the side.

**Comment by seichris** [comment]
Send ETH > "Select address" into  "Select contact"

**Comment by seichris** [comment]
Account > edit

delete the two options

**Comment by Kisgus** [comment]
Done.
