### ISSUE TITLE
Confirm payment screen

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#208]
### Issue description:

- Turn white closing-x into a dark one
- align beer icon
- remove the middle bar
- remove the spacing accordingly
- confirm button in new design

### Screenshots or mock-ups

![confirm and tl screens](https://user-images.githubusercontent.com/25006584/44908783-1d2dd580-ad1d-11e8-86f5-189a9cd07669.JPG)

**Comment by dakingha69** [comment]
Implemented via https://github.com/trustlines-network/mobileapp/compare/18070e36d819...af5e7f7afe35
