### ISSUE TITLE
Unable to read numbers while typing them.

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/feedback#211]
### Basic information:

* OS (Android / iOS / both): Samsung Galaxy Alpha - Android 4.4.4
* Version: 1.1.1 (1535733972), on production app called simply "Trustlines"

### Issue description:

When I go attempt to modify a trustline, I cannot read what number I am entering because it is covered by the keyboard, I also cannot scroll the screen up to see it. You can also see here that I cannot enter "19.50" as I do not have access to the ".". An issue was already created for it so I do not open a new issue.
Lastly, the title of the view is not centred.

### Screenshots or mock-ups

![photo_2018-09-03_16-17-01](https://user-images.githubusercontent.com/17010722/44991779-7ef87480-af95-11e8-9128-09bf304fbaf4.jpg)

**Comment by seichris** [comment]
Should be fixed with this mockup https://github.com/trustlines-network/feedback/issues/195#issuecomment-416269418

**Comment by seichris** [comment]
Being worked on in https://github.com/trustlines-network/feedback/issues/195
