### ISSUE TITLE
Show pending payment requests

### ISSUE THREAD

**Issue by czepluch** [trustlines-network/feedback#212]
### Basic information:

* OS (Android / iOS / both): android
* Version: 1.1.1

### Issue description:
I made a receive request, but I cannot see anywhere the requests I've made. This would be nice in order to see if people actually pay up what one requests. 

In the same way I also received a notification about somebody sending me a payment request, but when I opened the app, I couldn't find it anywhere.

**Comment by seichris** [comment]
Thanks Jacob, i completely agree.

To see which status the payment request is in (sent to relay; on blockchain; paid; partly paid) we should use the checkmarks. (Related to https://github.com/trustlines-network/project/issues/203)

@jensneuber is the info above enough to implement the features, both for sending and receiving payment requests?

**Comment by seichris** [comment]
We didn't yet implement a transaction id, for the sender to be able to see if his request was paid.
(link the existing issue)

Quick fix:
- we want to show the event to the sender. But we want to include the option to delete the event.
(will make a mockup)

**Comment by seichris** [comment]
Working on this in here: https://github.com/trustlines-network/mobileapp/issues/306
