### ISSUE TITLE
Confusing backup password

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#219]
### Basic information:

* OS (Android / iOS / both): 
Android 
* Version: 
1.1.2-dev.7
### Issue description:
Feedback from Tibor:
I was confused when the passphrase backup dialog popped up when pressing on receive payment. I thought I will have to do that every time. 

### Possible solution
We should better communicate for user what this passphrase is. Make clear that they have to write it done to get access to there account if they lose there phone, but that they only have to write it done once and hopefully never, or only very rare have to enter it. 
Idea for entering it is to have auto completion.

**Comment by seichris** [comment]
This issue will be worked on in the [onboarding flow](https://github.com/trustlines-network/mobileapp/issues/291).
