### ISSUE TITLE
No way of getting an overview of who owes you money. 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#220]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 
1.1.2-dev.7
### Issue description:
There is currently no way to show an overview of how the balance and the available amount is distributed. There should be a view for a network where you can see an overview of your balances to your contacts and how much they add to you available amount. 
Maybe we should split it up in people that owe you, people you owe to. Needs to be discussed. 
This was also something that Tibor mentioned.

**Comment by seichris** [comment]
Will be worked on in here: https://github.com/trustlines-network/mobileapp/issues/312
