### ISSUE TITLE
ETH Fees are subtract from EUR creditline

### ISSUE THREAD

**Issue by alexanderboerger** [trustlines-network/feedback#25]
### Basic information:

* OS (iOS): 
* Version: 

### Issue description:
Ok, I get the fees are converted from ETH to EUR for a better understanding, but I don't think we can subtract them from the creditline.

We should show fees in ETH ( EUR ).

Subtracting them from my creditline is clearly a bug

### Screenshots or mock-ups
![img_4883](https://user-images.githubusercontent.com/19476957/35690671-c06674d4-0776-11e8-8461-c68661399bbb.PNG)
![img_4882](https://user-images.githubusercontent.com/19476957/35690672-c0830838-0776-11e8-8759-e833922bb6ee.PNG)

**Comment by Kispus** [comment]
@alexanderboerger Do you fees in ETH should always be visible for regular users, who might not know to much about ETH, or rather only visible for advanced user e.g they click an expandable button or enable this feature under "settings" ??

**Comment by alexanderboerger** [comment]
I think the information (you have x transactions left) would be easier for non crypto people
