### ISSUE TITLE
Unknown User - SCAM?

### ISSUE THREAD

**Issue by alexanderboerger** [trustlines-network/feedback#26]
### Basic information:

* OS ( iOS): 
* Version: 

### Issue description:
(1) When I connect to more than one User at a time (Posting my link on FB) there is no way to figure out who is the user. 

(2) This brings me to ne next problem. If someone impersonates someone else or uses a vague name like "Chris" there is a high chance someone will accept a credit line from a SCAMMER

### Screenshots or mock-ups
![img_4884](https://user-images.githubusercontent.com/19476957/35690928-76ff1e8a-0777-11e8-8705-de041aeb4364.PNG)

### Possible solution

(1) make the username a musthave and do not lose it on the way
(2) Enable the linking to a Social Profile (like in keybase)

**Comment by Kispus** [comment]
**Description**

1) do you mean if you post it in a public visible group??

**Solution**

1) Right now we have just implemented auto-generated user-names, are you referring to "unique user-names in an ENS fashion" ?

2)  Do you refer to fx linking to fx a facebook profile?

**Comment by Kisgus** [comment]
We currently have no fix for this, at a later point more layers of identity could be included.
