### ISSUE TITLE
Sliderproblem

### ISSUE THREAD

**Issue by alexanderboerger** [trustlines-network/feedback#27]
### Basic information:

* OS ( iOS ): 
* Version: 

### Issue description:
When I try to slide the slider it happens that I move the UI

### Screenshots or mock-ups

![img_4881](https://user-images.githubusercontent.com/19476957/35691581-21265e0e-0779-11e8-9a71-0c726aa1d077.PNG)

### Possible solution

Make the slider Bigger or Disable the UI-Slide for the lower third of this screen

**Comment by Kisgus** [comment]
We could also just make the slider smaller?

![screen shot 2018-02-08 at 6 35 02 pm](https://user-images.githubusercontent.com/18598519/35988493-d071a2b2-0cfe-11e8-8385-ad9a5963f9c3.png)

**Comment by alexanderboerger** [comment]
I think one problem is that both functions need the same movement. I think your solution of changing the direction is much better.

**Comment by Kisgus** [comment]
Removed slider option
