### ISSUE TITLE
Onboarding & Fees in general

### ISSUE THREAD

**Issue by alexanderboerger** [trustlines-network/feedback#28]
### Basic information:

* OS (both): 
* Version: 

### Issue description:
I don`t think I would use the program if it cost me so much money the invite new users or to make a transaction. Especially when I don't need the security of the Blockchain.

### Possible solution

Cant we just make a free Testnet/private chain version and a paid on chain version? I think for 99% of the use cases the free version is ok.

**Comment by Kisgus** [comment]
@alexanderboerger yes agreed, this is not really a mobile app issue, but definitely a long-term scalability and cost issue which we are working on internally.
