### ISSUE TITLE
Show QR code, whenever the user wants to ad someone

### ISSUE THREAD

**Issue by alexanderboerger** [trustlines-network/feedback#29]
### Basic information:

* OS (iOS ): 
* Version: 

### Issue description:

Why don`t you just show the QR Code if the contacts page is empty? You can`t do anything else there anyway.

### Screenshots or mock-ups

![img_4879](https://user-images.githubusercontent.com/19476957/35692002-56202d00-077a-11e8-8e25-7134a5b74e9d.PNG)

**Comment by Kisgus** [comment]
Included, thanks
