### ISSUE TITLE
Pending creditline request shown in wrong currency networks. 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#3]
### Basic information first:

* OS (Android): 
* Version: 1.0.0.12

### Issue description:

After sending a creditline update request, the message "There already is a pending creditline..." on the contact view is not only shown in the right currency network but also in others.

**Comment by jensneuber** [comment]
please label your issues

**Comment by berndbohmeier** [comment]
I cant, no permission :(

**Comment by Kispus** [comment]
Tested on iOS & Android on two new fresh accounts, and a creditline request in the Euro network is no longer shown within the other networks.
