### ISSUE TITLE
Text sent with Trustlines Network URL is formatted incorrectly

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#30]
### Basic information:

* OS (Android / iOS / both): 
* Version: 
7.1.1

### Issue description
When a Trustlines Network URL is shared on another application, the message included is formatted incorrectly

### Screenshots or mock-ups
![screenshot_20180202-141824 1](https://user-images.githubusercontent.com/29100596/35737564-444b32d4-082c-11e8-9b07-de369392eb2c.png)

### Possible solution

Change current format: 
STANDARD TEXT, OPTIONAL MESSAGE, :,  AMOUNT DENOMINATION, URL, OPTIONAL MESSAGE
to
STANDARD TEXT, AMOUNT DENOMINATION, OPTIONAL MESSAGE, URL

**Comment by Kisgus** [comment]
Tested with Chris and should be fixed now, please re-open if this is not the case
