### ISSUE TITLE
Our Favorite Signup Process

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#31]
We open the app, sign up.

What is the first screen we see?

A nice bonus is text or mockups.

**Comment by seichris** [comment]
1. terms and conditions
2. load indicator in the background. so i got time to slide through all the pics
3. first screen should be home screen.
- text should be in the style of the notifications / events later.
- include explanation "this is the homescreen. here you will see all transactions and trustlines with your friends."
- include "do you want to receive ETH?" `qr code.icon` to click to become larger.
- include other options, like send, receive. change network

**Comment by Kisgus** [comment]
@seichris I like your tutorial approach. A few questions:

1) Where would you put the QR code icon? Could you provide an example?
2) How about "Share link" or Copy?
3) Would these other options be similar to how they already look like on "Home" ?

**Comment by Kisgus** [comment]
Would you also see these options ad slide-able like you suggested here @seichris ??

https://github.com/trustlines-network/feedback/issues/15

**Comment by seichris** [comment]
1. the same place where the QR code is in the `Profile` screen too. preferably in the top right corner.
Then you could do an overlay which points to the icon.

2. I don't like the share feature. Always gets messed up on my phone. Its not standardized.
I would show the ETH address and a copy button next to it. Or copyable through long click.
Put it in the same text box as the intro explanation

3. the other options can be placed the same. send - receive ...
the sliding design should just be used for additional info, which normally would be on another screen.
