### ISSUE TITLE
My preferred Signup

### ISSUE THREAD

**Issue by alexanderboerger** [trustlines-network/feedback#32]
Open App
Watch a short video (with subtitles) what is trustlines
Create wallet
I will be asked to change my name, the change is easy
I get offered the chance to back up my account
After 10 sec of Text I understand why this is important
Create a Trustline = Find a friend
My link & QR code will be shown
A friend scans the code, I get an instant notification when I got onboard.
I can accept the creditline

**Comment by Kisgus** [comment]
@alexanderboerger so would the first screen be "Home", "Profile" or something different??

**Comment by alexanderboerger** [comment]
@Kisgus first screen after what?
