### ISSUE TITLE
After restarting app changed language to Chinese

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#35]
### Basic information:

* OS (Android / iOS / both):  Android
* Version:  7.1.1

### Issue description:
The app changed its UI language to Chinese after being restarted

### Screenshots or mock-ups
![image](https://user-images.githubusercontent.com/29100596/36041817-0adccdf2-0dca-11e8-8f34-55627c9d0626.png)

**Comment by jensneuber** [comment]
Iconfont was missing. Closed
