### ISSUE TITLE
Pending creditline request shown after it was excepted

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#4]
### Basic information first:

* OS (Android): 
* Version: 1.0.0.12

### Issue description:
I can not see the creditlines in my contact view even after the creditline request was excepted. I can confirm that it happened because my available amount increased, but I still see the "Pending request" message in the contact view instead of the trustlines. 

### Screenshots

*please provide screenshots on any UI related issue*

**Comment by jensneuber** [comment]
fixed with trustlines-network/feedback/issues/2

**Comment by Kispus** [comment]
Tested on iOS & Android. Currently an active creditlines and trustlines are visible in the EURO network. If I however switch to the dollar network, they are still visible under this network. Closing this issue and creating new dedicated issue on the new bug identified.
