### ISSUE TITLE
Spelling issues 

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#40]
### Basic information:

* OS (Android / iOS / both):  Android
* Version: 7.0

### Issue description:
- Currency symbols should be before numeric value: e.g. € 5.00
- Show QR Code -> show QR code (see screenshot 

### Screenshots
1.
![spelling](https://user-images.githubusercontent.com/29100596/37465450-6e9474b6-285b-11e8-92d5-b6a120f259e1.png)

**Comment by Kisgus** [comment]
@krisnaer I believe having currency symbol before is typical american, classic british style, and euro forexample can be put behind it as well, from a design perspective I think it is a bit eaiser to align all the symbols on a single line in the back

**Comment by Kisgus** [comment]
Fixed
