### ISSUE TITLE
Formatting for trustlines agreements (not sure if intentional)

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#42]
### Basic information:

* OS (Android / iOS / both): Android
* Version: 7.00

### Issue description:

- Curreny symbol spaced oddly far away from value (also in wrong order) 
- Unknown is in blue, while my user name is in grey

### Screenshots or mock-ups
![formatting off](https://user-images.githubusercontent.com/29100596/37465715-30687ef2-285c-11e8-90ba-f4705f6a3d19.png)

**Comment by Kisgus** [comment]
As I am aware currency symbol can be up to discussion, please see comment to #40 

The "blue ink" is intended to symbolize the counter-party has already signed it, while you have not yet, if you are signing it, both will be blue.

**Comment by Kisgus** [comment]
@krisnaer closing as a comprehensive issue on layout of trustline agreements is in progress
