### ISSUE TITLE
Poor back options for mnemonic phrase

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#43]
### Basic information:

* OS (Android / iOS / both):  Android
* Version: 7.00

### Issue description:
Backing up my mnemonic phrase takes me to a sharing option of services that are not good for this feature (e.g. sending it as a status update on facebook)

### Screenshots or mock-ups
![backup poorly shared](https://user-images.githubusercontent.com/29100596/37466047-1c7414fa-285d-11e8-8c1f-83eca2f182f9.png)

### Possible solution

Customize offered services and add warning label. For example: "Anyone who has these words can recover your wallet. Only store them in a place you have control over."

**Comment by Kisgus** [comment]
To be changed with https://github.com/trustlines-network/mobileapp/issues/150
