### ISSUE TITLE
Backup warning dialogue is written on top of the "password" button under "ME"

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#44]
### Basic information:

The warning dialogue that says "your account is at risk" is written on top of the "password" button

* OS (Android / iOS / both): Android
* Version: 7.00

### Screenshots or mock-ups
![screenshot_20180315-115506](https://user-images.githubusercontent.com/29100596/37466589-69b56f7e-285e-11e8-8001-2afa976e85a5.png)

**Comment by Kisgus** [comment]
Fixed
