### ISSUE TITLE
App crashes when clicking identicons

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#45]
### Basic information:

* OS (Android / iOS / both):   Only Android (Sony & Xiaomi)
* Version:  Newest

### Issue description:

When the "clickable options" become visible after pressing any identicon, the app crashes if one press outside of the "options box"

### Screenshots or mock-ups

![screenshot_2018-03-15-15-51-47](https://user-images.githubusercontent.com/18598519/37470974-0d95910a-2869-11e8-9544-f5d9fc53294e.png)

### Possible solution

When the user press outside the box here to make this action equivalent to pressing "Close"

**Comment by jensneuber** [comment]
solved

**Comment by Kisgus** [comment]
Done ty!
