### ISSUE TITLE
List of minor design and bug fixes

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#50]
### Basic information:

* OS (Android / iOS / both): Newest
* Version:  **Android: 1.0.17/v9**    & **iOS: 1.0.17/v25**

### Issue description:

Please find below a list of minor bugs including screenshot and link to relevant issues:

## Align list view on "Overview", "Trustlines" "Me" pages

**Me** (How it should be)

![img_3290](https://user-images.githubusercontent.com/18598519/38304797-ebf28038-380a-11e8-8b50-007bae8bad82.png)

**Truslines** (Align with list view as Me)

![img_3289](https://user-images.githubusercontent.com/18598519/38304833-039b41de-380b-11e8-9c85-1400b5ce7e69.png)

**Overview** (Align with list view as Me)

![img_3291](https://user-images.githubusercontent.com/18598519/38304837-05bb7b82-380b-11e8-944a-a6c379e6a4db.png)

## Write the currency network name on Available instead of displaying symbol

So on the above "Overview" screen write 0.00 US Dollar instead of $

## *Change "Support" naming to "Feedback" on the  "Me" page

And list the 3 new lists in the following order:

- FAQ

- Feedback

- Community

## When pressing FAQ from "Me" the "FAQ" page needs to be capitalized instead of "Faq"

Next :)

## Include "Next / back" button on trustlines agreement keyboard

![img_3286](https://user-images.githubusercontent.com/18598519/38304932-57a9168e-380b-11e8-864a-e52989bdd9b9.png?s=200)

What happend to these buttons? I remember we discussed it ? :)

## **Polish "Receive ETH"

Described in https://github.com/trustlines-network/feedback/issues/38

## **Fix android crash

Described in https://github.com/trustlines-network/feedback/issues/45

## **Delete 2nd start-up loading icon

Described in https://github.com/trustlines-network/feedback/issues/37

**Comment by jensneuber** [comment]
I consider this issue done

**Comment by Kisgus** [comment]
Me too! TY!
