### ISSUE TITLE
Receive trustlines money flow

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#53]
### Basic information:

* OS (Android / iOS / both): Newest Android version

### Issue description and solution

**Initiator**

- [ ] The QR code on "Receive payment" screen goes from small to big.

- [ ] The number that is received should be centered in the middle

**Person scanning QR code**

- [ ] If possible display number of hops

**Initiator**

- [ ] Receives the transaction two times, blue "notification dot" not disappearing 

- [ ] Receives the amount requested + the ETH fees

**Comment by jensneuber** [comment]
I consider this issue done

**Comment by Kisgus** [comment]
Okay works thanks, created a dedicated issue on the URL fomatting of receive ETH  in #76
