### ISSUE TITLE
Changes to "Global navigation" sidebar

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#55]
### Basic information:

* OS (Android / iOS / both): Both
* Version: Newest

### Issue description:

We currently do not have any + symbol on the "Trustlines" page anymore for "adding a contact".
@chris suggest that we change the symbol of the global navigation bar to a + on the Overview, Trustlins & Me page and include the "Add Contact" feature here.

### Screenshots or mock-ups

![img_3293](https://user-images.githubusercontent.com/18598519/38369503-23ea9664-38e8-11e8-9c5b-b5b56b8bad1a.png)

### Possible solution

Replace the burger icon with a + icon for the global navigation bar and add the "Add contact" as an option to the global navigation bar.

**Comment by jensneuber** [comment]
@Kisgus I consider this issue done ..

**Comment by Kisgus** [comment]
Same here, thanks!
