### ISSUE TITLE
Fees on payment receipt not visible 

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#57]
### Basic information:

* OS (Android / iOS / both): Both
* Version:  Newest

### Issue description:

Only the name "Fees" displayed rather than the actual test-ETH fees

### Screenshots or mock-ups

![img_3297](https://user-images.githubusercontent.com/18598519/38371152-0366ae10-38ec-11e8-9eaa-31042b8b4bad.png)

### Possible solution

Include the nominal fees paid in test-ETH

**Comment by jensneuber** [comment]
As far as I see it, this info is not available

**Comment by Kisgus** [comment]
Okay @jensneuber I would assume this is available from forexample etherscan? Can you please clarify why that is not the case

**Comment by Kisgus** [comment]
Also covered in https://github.com/trustlines-network/mobileapp/issues/184
