### ISSUE TITLE
Transaction history is not loaded in overview upon restarting of app

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#58]
### Basic information:

* OS (Android / iOS / both): Android
* Version: 8.0.0

### Issue description:

- Upon closing app, Overview screen does not fetch previous transaction history. 
- Instead, loading icon runs indefinitely (notice loading icon in  the middle of the screen in the screenshot provided below)
### Screenshots or mock-ups

![photo5922290264146291653](https://user-images.githubusercontent.com/29100596/38371353-817becca-38ec-11e8-8074-274fc41aae87.jpg)

**Comment by jensneuber** [comment]
This should be solved. The timeout for requesting the events was 10 sec., is now 30 sec.
