### ISSUE TITLE
The app states "Direct connection found" for multi-hop payment

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#59]
### Basic information:

* OS (Android / iOS / both): Both
* Version:  Newest

### Issue description:

We experimented with a multi-hop transfer, but for the sender (Kris) the confirm screen still titled "direction connection found"

### Possible solution

Just like in the PoC_v1 the confirm screen should accurately state "Connection through 1 person" (if that is the case)

**Comment by jensneuber** [comment]
Since we do net really get this information from the relay server re removed the displayed line completely
