### ISSUE TITLE
Signup Process

### ISSUE THREAD

**Issue by alexanderboerger** [trustlines-network/feedback#6]
### Basic information first:

* OS ( iOS ): 
* Version: 1.0.15

### Issue description:

I don't like to press return before I can click the signup button, it should be available while the keyboard is visible

### Screenshots

![img_4868](https://user-images.githubusercontent.com/19476957/35388031-79778c06-01d2-11e8-8c55-0d5438f2d8b3.PNG)

*please provide screenshots on any UI related issue*

**Comment by Kispus** [comment]
Yes I agree, we could consider only linking to the Terms of Use.

**Comment by Kispus** [comment]
Something like this @alexanderboerger ??

![img_2996](https://user-images.githubusercontent.com/18598519/35510760-b1df7d9a-04f9-11e8-92de-a8d7d4c7b6c7.PNG)

How about having the Terms of Use on this screen, do you think that works as it is now?

**Comment by alexanderboerger** [comment]
thats all it needs, you might want to change the color from grey to green after name & email are filled

**Comment by Kispus** [comment]
@alexanderboerger The question is really if we also need to ask the user to choose a username, or if we can just skip this step as well and auto-generate a user-name in first instance?

**Comment by Kispus** [comment]
How about this **Signing Up flow** @alexanderboerger ?

### Entering app load screen

![screen shot 2018-01-31 at 11 41 23 am](https://user-images.githubusercontent.com/18598519/35618591-ba68571a-067b-11e8-9065-ae0e613eaf88.png)


### Sign up screen with 3/4 tutorial carrousel

![screen shot 2018-01-31 at 11 07 00 am](https://user-images.githubusercontent.com/18598519/35618600-c05d8348-067b-11e8-8b0c-c1b09f187606.png)

### Terms of Use when pressing "Sign Up"

![screen shot 2018-01-31 at 11 37 01 am](https://user-images.githubusercontent.com/18598519/35618635-d6c59a80-067b-11e8-9387-84dd17d7375e.png)


### Direct to onboarding "Profile" with auto-generated-name

![screen shot 2018-01-31 at 11 25 00 am](https://user-images.githubusercontent.com/18598519/35618727-174cd488-067c-11e8-9eb1-9f76015630a2.png)

**Comment by alexanderboerger** [comment]
I would ad a pencil instead of the arrow, but this is a good way

**Comment by seichris** [comment]
Different problem, but same solution:

Problem:
User wants to see the name of the other person, who onboards her.
Solution:
Auto-generated name, which is visible for everyone in the network. Could come from server or from smart contract. (Like ENS)

**Comment by Kispus** [comment]
Reviewed and works 90 % as intended, still design issues remaining, we will fix it friday.
