### ISSUE TITLE
When typing in amount (send or receive), cursor is centered on top of numeric example

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#60]
### Basic information:

* OS (Android / iOS / both): Android
* Version:  8.0.0

### Issue description:
The cursor is placed in the center of the screen where the numeric example (0.00) is also placed. The cursor ends up being on top of the example which looks wrong. Please see the screenshot for details

### Screenshots or mock-ups

![28e2787f-e86d-4aa6-905b-3f991decfe7a](https://user-images.githubusercontent.com/29100596/38375338-440f25c8-38f6-11e8-91b1-26293b602806.jpeg)

### Possible solution
-  Move the cursor to the right of the numeric example or remove the cursor until the user presses on the numeric example 
- (style suggestion) give the cursor width like a command line interface cursor has.

**Comment by Kisgus** [comment]
Not centered anymore
