### ISSUE TITLE
Chevron in sidebar is appearing and disappearing 

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#61]
### Basic information:

* OS (Android / iOS / both): iOS
* Version: 1.0.17 / v28

### Issue description:

**When entering the app the sidebar looks like this (with chevron)**

![img_3300](https://user-images.githubusercontent.com/18598519/38408590-75d35786-397e-11e8-8c7e-0491a387feac.png)

**When clicking the testcoin network (disappearing)**

![img_3301](https://user-images.githubusercontent.com/18598519/38408607-88da051e-397e-11e8-87ef-a4d8807d34ce.png)

### Possible solution

Remove the chevron :)

**Comment by jensneuber** [comment]
Done
