### ISSUE TITLE
Onboarding tutorial-text reappears when entering app

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#64]
### Basic information:

* OS (Android / iOS / both): Android
* Version: 1.0.18

### Issue description:

The "onboarding" tutorial text pop's up again now and then, even though the account has been active in a currency network - see  fx below an example where the account already has Euro available.

### Screenshots or mock-ups

![img_3317](https://user-images.githubusercontent.com/18598519/38726968-fb81ac6a-3f0b-11e8-9990-57092a9aca49.jpg)

### Possible 

Tutorial text should only be visible before a user has any active trustlines

**Comment by seichris** [comment]
@kisgus is this still relevant?

**Comment by Kisgus** [comment]
No, I am closing
