### ISSUE TITLE
Sidebar UI

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#7]
### Basic information first:

* Android 7.0 - MIUI 9 - Xiaomi 5S

### Issue description:
Sidebar looks confusing.
- Less variance in colors. extreme: just one background color. may divide by small lines
- no "show only my networks", but show all the networks

### Screenshots
![tl sidebar](https://user-images.githubusercontent.com/25006584/35388101-ba2cef48-01d2-11e8-88e1-14e8e32d38ad.jpg)

**Comment by Kispus** [comment]
How about this @seichris ??

![screen shot 2018-01-29 at 1 32 52 pm](https://user-images.githubusercontent.com/18598519/35510584-f25c853a-04f8-11e8-931f-e0f9e7fa0824.png)

Would you change anything on this?

**Comment by seichris** [comment]
looks good

**Comment by jensneuber** [comment]
Which one is the selected network? Shouldn't there be some indicator?

**Comment by jensneuber** [comment]
A new place for discovering / selecting new networks is needed as well.

**Comment by Kispus** [comment]
![screen shot 2018-01-31 at 9 27 50 am](https://user-images.githubusercontent.com/18598519/35612431-0c2fe03a-0669-11e8-8551-655ba029ac43.png)

This should balance both your points @jensneuber & @seichris

**Comment by Kispus** [comment]
Tested and works, only design element of location of "Asset" remaining
