### ISSUE TITLE
Unicorn loading logo coming up now and then

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#70]
### Basic information:

* OS (Android / iOS / both):  Android
* Version:  1.0.18 / v16

### Issue description:

The unicorn loading icon keeps coming back up on white background now and then, for-example when pressing "receive eth" 

### Screenshots or mock-ups

Tried, but it only pops up very briefly before disappearing 

### Possible solution

Remove the sign up loading icon on white background to pop up

**Comment by jensneuber** [comment]
This is the background of the Android App and this is the only way right now to have the logo showing while loading the app. Needs more research to solve.

**Comment by seichris** [comment]
moved to here https://github.com/trustlines-network/design/issues/24
