### ISSUE TITLE
App crashes when opening in telegram to request for TEST_ETH

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#77]
### Basic information:
I cannot onboard my friend to trustlines because I do not have ETH. I'm presented with the option to open up telegram and request ETH. After pressing the button to open Telegram, the app crashes

* OS (Android / iOS / both): Android 
* Version: 8.0.0

**Comment by jensneuber** [comment]
With a crash like this I need a crash report

**Comment by Kisgus** [comment]
Cannot reproduce any longer on any android device
