### ISSUE TITLE
Update default sharing telegram group from "Trustlines Testing" to "Trustlines Network"

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#78]
### Basic information:

* OS (Android / iOS / both):  Both
* Version: N/A

### Issue description:

 - When sharing a link in the default Trustlines group, the app still selects "Trustlines Testing".  This should be updated to the official Telegram group (https://t.me/trustlines_network).

**Comment by Kisgus** [comment]
Thanks
