### ISSUE TITLE
start screen UI

### ISSUE THREAD

**Issue by seichris** [trustlines-network/feedback#8]
### Basic information first:

* Android 7.0 - MIUI 9 - Xiaomi 5S

### Issue description:
start screen should have some description of Trustlines already

### Screenshots

![tl start](https://user-images.githubusercontent.com/25006584/35388263-5c6000ac-01d3-11e8-8969-51b54fba8f61.jpg)

**Comment by Kispus** [comment]
@seichris How do you mean? Like a tagline, a sequence of tutorial or in what sense?

**Comment by seichris** [comment]
not just a tagline. but 3 or 4 swipeable screens, explaining some TL concept

**Comment by jensneuber** [comment]
hmm, I suggest the app store description / website for in depth explanation.
a rather small indicator, that the user can swipe left to see some tutorials might be a solution

**Comment by Kispus** [comment]
@seichris for pictures  /  retina solution ( 250 - 300 dpi)

**Comment by Kispus** [comment]
First draft of proposals have been made here. 

https://docs.google.com/presentation/d/1hmcQPlLMmwJM40VZmwxfw7cAqQ85J6GnPYkQr9SMSuU/edit?usp=sharing

@seichris please export the pictures in retina solution ( 250 - 300 dpi)

**Comment by Kispus** [comment]
I see your point @jensneuber we could also add such explanation pictures in the app-stores as well. In any case the first step would be to actually have some explanation screens, which we can then iterate, and eventually choose to locate the one an/or other place

**Comment by Kispus** [comment]
Updated graphical pictures @jensneuber 

https://docs.google.com/presentation/d/1hmcQPlLMmwJM40VZmwxfw7cAqQ85J6GnPYkQr9SMSuU/edit?usp=sharing
https://drive.google.com/drive/folders/1Bgu0LV7u2Iy8fKiTXmWKXIs0Zzl9UwOG?usp=sharing

**Comment by Kispus** [comment]
@jensneuber this is my best take on 3 [very minimum viable] tutorial screens 

**1**

![screen shot 2018-01-30 at 6 35 03 pm](https://user-images.githubusercontent.com/18598519/35581862-6bb91818-05ed-11e8-9806-0c04105e3d96.png)

**2**

![screen shot 2018-01-30 at 6 35 22 pm](https://user-images.githubusercontent.com/18598519/35581945-9e27df0a-05ed-11e8-8856-a9a197e28bd3.png)

**3**

![screen shot 2018-01-30 at 6 37 52 pm](https://user-images.githubusercontent.com/18598519/35581960-a2ca0330-05ed-11e8-84e8-0101fa062e75.png)


**For original pictures**

**Comment by alexanderboerger** [comment]
Just thought we would hide the Blockchain part

**Comment by alexanderboerger** [comment]
In Image 2 I would expect more explanation. I think the user needs to understand that we will move one balance after another.

**Comment by Kispus** [comment]
@alexanderboerger okay, just another screen to elaborate on this or how do you mean?

Maybe we can find a compromise between and the very detailed number of screens you provided in our first draft :)

**Comment by Kispus** [comment]
Description implemented as requested @seichris, but this certainly have to be made prettier, this will go into a dedicated issue.
