### ISSUE TITLE
FAQ issues list (pixelated picture) (moveable frame) 

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#80]
### Basic information:

me>FAQ 
links to the website's FAQ. The site is not optimized for mobile

* OS (Android / iOS / both): Android
* Version: 8.0.0

### Screenshots or mock-ups
Menu button is not optimized for screen width (I need to scroll to the right to see the button)
![image](https://user-images.githubusercontent.com/29100596/39255580-2ad82b38-48ad-11e8-87fe-9df9d3c2d882.png)

- Is the menu even needed? It appears to contain the entire website. Consider restricting the view to the FAQ
- FAQ should be capitalized (the menu header reads "Faq") 
![image](https://user-images.githubusercontent.com/29100596/39255681-61541d20-48ad-11e8-9f71-36a2e6d0e4a3.png)

The background image is not optimized for mobile and is very pixellated. consider removing it and replacing it with white or grey (same color scheme as in-app)
![image](https://user-images.githubusercontent.com/29100596/39255730-854be3c0-48ad-11e8-82fb-a23cc260c018.png)

### Possible solution
@Kisgus please look over my suggestions and make a decision

**Comment by jensneuber** [comment]
Should be solved
