### ISSUE TITLE
Trustlines opens in Telegram Window (android)

### ISSUE THREAD

**Issue by krisnaer** [trustlines-network/feedback#81]
### Basic information:

When I open a link using Telegram. The TL Staging app is opened in a hidden window in Telegram

* OS (Android / iOS / both): Android
* Version: 8.0.0

### Screenshots or mock-ups

![image](https://user-images.githubusercontent.com/29100596/39256511-68444144-48af-11e8-8231-3f414802010d.png)

When browsing through running applications, Trustlines is gone from the applications list and instead the UI is displayed under Telegram. If I press Telegram, Trustlines will open. However, I cannot go back into Telegram without crashing Trustlines.

**Comment by jensneuber** [comment]
More info is needed

**Comment by Kisgus** [comment]
Cannot reproduce
