### ISSUE TITLE
Crash from Scanner

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/feedback#82]
### Basic information:

* OS (Android / iOS / both):  Android
* Version: 4.4.4
* Phone: Samsung galaxy alpha SM-G850F

### Issue description:
I open the application, go to the scanner tab, and it crashes ("TL-Staging stopped working"). Note that the scanner did not show what my camera should have shown before crashing (like no access to my camera). But the scanner tabs opens for 0.2 second and I can see the white crosshair for that time.

### Screenshots or mock-ups
I don't have time to take a screenshot before it crashes

**Comment by Kisgus** [comment]
@andfletcher has the same error on Samsung Galaxy S9

**Comment by Kisgus** [comment]
Tested and scanner now works flawless on Android
