### ISSUE TITLE
Cannot send TEST-ETH by scanning QR code

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#83]
### Basic information:

* OS (Android / iOS / both): iOS
* Version: Newest

### Issue description:

I am not able to scan an "Receive ETH" QR code, there is simply no responds from my phone (see screenshot)

### Screenshots or mock-ups

![img_3465](https://user-images.githubusercontent.com/18598519/40621758-74a66ad0-629e-11e8-8560-6ae5499a6239.png)

### Possible solution

Enable me to send ETH :)

**Comment by jensneuber** [comment]
solved
