### ISSUE TITLE
Currency network slider shrinks for every time being opened

### ISSUE THREAD

**Issue by Kisgus** [trustlines-network/feedback#85]
### Basic information:

* OS (Android / iOS / both):  iOS only
* Version: Newest

### Issue description:

For every time I open the currency network slider, it gets smaller, see below

### Screenshots or mock-ups

![img_3469](https://user-images.githubusercontent.com/18598519/40621692-28552e0a-629e-11e8-94c3-dc252ab5c239.png)

 
### Possible solution

Fix the size of the currency network slider

**Comment by jensneuber** [comment]
not reproducible for now. more info needed

**Comment by Kisgus** [comment]
Okay, will show you tomorrow @jensneuber :)

**Comment by seichris** [comment]
implemented
