### ISSUE TITLE
Currency overview crashes app

### ISSUE THREAD

**Issue by andfletcher** [trustlines-network/feedback#87]
### Basic information:

* OS (Android): 
* Version: N/A

### Issue description:
If i click on "Me" and then "currency" the app crashes

**Comment by jensneuber** [comment]
Can you give me some more info on this? Maybe also include a crash report

**Comment by andfletcher** [comment]
It appears that this bug is not active any more since i updated my phone. Will investigate further.

**Comment by krisnaer** [comment]
* OS (Android): 8.0.0

Could not reproduce this bug

**Comment by Kisgus** [comment]
Tested and works on iOS / Android phone
