### ISSUE TITLE
Deleting of Contact with trustline not working

### ISSUE THREAD

**Issue by andfletcher** [trustlines-network/feedback#88]
### Basic information:

* OS (Android): 
* Version: 

### Issue description:
If i delete a contact that i have a trust line with i have to close it bevor. 
Also if it is closed and i then delete it, the history will stay in the app and the contact name will change to "unknown" 

### Possible solution
Let the delete function automatically close the trustline
Delete contact completely or change app in a way that you can view past transactions / trustlines / contacts in another way. The current solution in renaming the contact to unknown is no good solution

**Comment by andfletcher** [comment]
![screenshot_20180528-155710_tl-staging](https://user-images.githubusercontent.com/39694712/40661224-7a00cdb2-6353-11e8-81c6-1406c8aeb15e.jpg)

**Comment by jensneuber** [comment]
This is done like this by design. Since we are on a blockchain that is not forgetting the transactions a user had with another, we are showing at least address (Unknown)

**Comment by andfletcher** [comment]
Okay, but their needs to be a better way in displaying this? I can not Imaging it is very user friendly if he has multiple unknown contacts within the app?

**Comment by Kisgus** [comment]
@andfletcher I am re-opening this issue in trustlines mobile app repo, you are very welcome to propose your solution there, but this is not a bug, as it is how the current design works
