### ISSUE TITLE
Can not decline a trustline request

### ISSUE THREAD

**Issue by andfletcher** [trustlines-network/feedback#91]
### Basic information:

* OS (Android): 
* Version: 

### Issue description:
I can not decline a trustline request. I con only change it so that the balance of the trustline is 0

### Possible solution

Quick fix: Implement a "Decline" button next to the "Agree" button which exits the screen and directs the user to "Overview"

**Comment by Kisgus** [comment]
There is now included a Decline button, but the invitation is still there
