### ISSUE TITLE
Click on show etherscan copies to clickboard

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#94]
### Basic information:
* OS (Android / iOS / both):
Android 
* Version:
1.0.17 v26 

### Issue description:
When on the profile view, clicking on show on etherscan results in a copy to clipboard action

**Comment by jensneuber** [comment]
Can you give more info and detail?

**Comment by Kisgus** [comment]
![img_3506 2](https://user-images.githubusercontent.com/18598519/41458124-0599a580-7086-11e8-8887-b93218dd1c24.png)

@jensneuber When clicking "Show on etherscan" from Me / Edit above happens instead of directing to etherscan

**Comment by jensneuber** [comment]
fixed

**Comment by Kisgus** [comment]
Tested and works on iOS / Honor Android phone
