### ISSUE TITLE
Clicking on the identicon in the trustlines view should also allow to go to account

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#97]
### Basic information:

* OS (Android / iOS / both): 
* Version: 

### Issue description:
When receiving a trustline request, what opens is the trustlines view where you can edit the credit lines amount, but there is no way to change the name of the other account. It would be intuitive to be able to click on the identicon or on the name directly.

**Comment by Kisgus** [comment]
Included in https://github.com/trustlines-network/mobileapp/issues/203
