### ISSUE TITLE
In the contact view clicking the name opens the keyboard but you can not edit the name

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/feedback#98]
### Basic information:

* OS (Android / iOS / both): 
Android
* Version: 
1.0.18 v26

### Issue description:
In the contact view clicking the name opens the keyboard but you can not edit the name. You have to click edit to do that. But it is weird that the keyboard opens.

**Comment by Kisgus** [comment]
Included in https://github.com/trustlines-network/mobileapp/issues/203
